import { Component } from '@angular/core';
import { 
  SimpleSliderComponent,
  AlphabetSliderComponent,
  CustomCombineLabelsFunctionSliderComponent,
  CustomDisplayFunctionSliderComponent,
  CustomHtmlDisplayFunctionSliderComponent,
  CustomLegendFunctionSliderComponent,
  CustomScaleSliderComponent,
  CustomTicksLegendSliderComponent,
  CustomTicksSliderComponent,
  DateSliderComponent,
  DisabledNormalisationSliderComponent,
  DisabledSliderComponent,
  DraggableRangeOnlySliderComponent,
  DraggableRangeSliderComponent,
  DynamicColorSelectionBarSliderComponent,
  DynamicOptionsSliderComponent,
  DynamicPointerColorSliderComponent,
  DynamicTickColorSliderComponent,
  FloatingPointSliderComponent,
  IntermediateTicksSliderComponent,
  IntermediateTicksValuesRangeSliderComponent,
  LimitedRangeSliderComponent,
  LimitedSliderComponent,
  LogScaleSliderComponent,
  ManualRefreshSliderComponent,
  NoSwitchingRangeSliderComponent,
  PushRangeSliderComponent,
  RangeSliderComponent,
  ReactiveFormRangeSliderComponent,
  ReactiveFormSimpleSliderComponent,
  ReadOnlySliderComponent,
  RightToLeftSliderComponent,
  SelectionBarAtEndSliderComponent,
  SelectionBarFromValueSliderComponent,
  SelectionBarGradientSliderComponent,
  SelectionBarSliderComponent,
  SteppedSliderComponent,
  StyledSliderComponent,
  TicksCustomTooltipsSliderComponent,
  TicksSliderComponent,
  TicksTooltipsSliderComponent,
  TicksValuesRangeSliderComponent,
  TicksValuesSliderComponent,
  TicksValuesTooltipsSliderComponent,
  TriggerFocusSliderComponent,
  UserEventsSliderComponent,
  VerticalSlidersComponent
 } from './snippets';

@Component({
  selector: 'app-demos',
  templateUrl: './demos.component.html',
  styleUrls: ['./demos.component.scss'],
  standalone: true,
  imports: [
    SimpleSliderComponent,
    AlphabetSliderComponent,
    CustomCombineLabelsFunctionSliderComponent,
    CustomDisplayFunctionSliderComponent,
    CustomHtmlDisplayFunctionSliderComponent,
    CustomLegendFunctionSliderComponent,
    CustomScaleSliderComponent,
    CustomTicksLegendSliderComponent,
    CustomTicksSliderComponent,
    DateSliderComponent,
    DisabledNormalisationSliderComponent,
    DisabledSliderComponent,
    DraggableRangeOnlySliderComponent,
    DraggableRangeSliderComponent,
    DynamicColorSelectionBarSliderComponent,
    DynamicOptionsSliderComponent,
    DynamicPointerColorSliderComponent,
    DynamicTickColorSliderComponent,
    FloatingPointSliderComponent,
    IntermediateTicksSliderComponent,
    IntermediateTicksValuesRangeSliderComponent,
    LimitedRangeSliderComponent,
    LimitedSliderComponent,
    LogScaleSliderComponent,
    ManualRefreshSliderComponent,
    NoSwitchingRangeSliderComponent,
    PushRangeSliderComponent,
    RangeSliderComponent,
    ReactiveFormRangeSliderComponent,
    ReactiveFormSimpleSliderComponent,
    ReadOnlySliderComponent,
    RightToLeftSliderComponent,
    SelectionBarAtEndSliderComponent,
    SelectionBarFromValueSliderComponent,
    SelectionBarGradientSliderComponent,
    SelectionBarSliderComponent,
    SteppedSliderComponent,
    StyledSliderComponent,
    TicksCustomTooltipsSliderComponent,
    TicksSliderComponent,
    TicksTooltipsSliderComponent,
    TicksValuesRangeSliderComponent,
    TicksValuesSliderComponent,
    TicksValuesTooltipsSliderComponent,
    TriggerFocusSliderComponent,
    UserEventsSliderComponent,
    VerticalSlidersComponent
  ]
})
export class DemosComponent {
}
